import base64
import binascii
from datetime import datetime

UPLOAD_FOLDER = 'uploads/'

# 原始 Base64 数据（已处理换行符）
base64_str = "/9j/4AAQSkZJRgABAQEAAAAAAAD/2wBDAAwICQsJCAwLCgsODQwOEh4UEhEREiUaHBYeLCYuLSsmKikwNkU7MDNBNCkqPFI9QUdKTU5NLzpVW1RLWkVMTUr/2wBDAQ0ODhIQEiMUFCNKMioySkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkr/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3Q=dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/8AAEQgA8AFAAwEhAAIRAQMRAf/aAAwDAQACEQMRAD8A82pKewhMUd6QC0tAhKSiwxaKACigYUUCEooASjFABRTAKKTAKKQgopjCkoAWkoAKKAEooAWkoGFJQIKKAJqSmAlFAhaKVhAKKBhRQMKKAEooELRQISimUFJQAUUhBSUALRQMSigBcU2gAooGFFAgooAKSgQUUDJqSgQlLQwEpaQBRTEFFBQUlMQUtIBKKBhSUwCikgCigQUGgYlFABRQAUlABRQAUYosAUUCCigBKKdiiWikQJRTHcKUUgCigYUlAC0lABRQIKKBhRQwCkoAKKLgFFABSUdACigApKACigAooAKKBCUUxhSUDJ8UlIkTtRRuMKWgQUUAFFIApKYwpaLgNpaQxKWgQlFMAopCCimAUlABRQMKSgYUUCCigQUUhhSUwCkoBE9NpoQYooAMUUmMKKAFpKACloGJRQSFFACUtAxKKBBRQMKKBCUUDCkoQC0lAgooAKSgAooAKKBiUUAT0lACUUxBRSAKKBhS0AJRQAUlAC0UAJ3paAEooAKKQCUUwCigAooASigAooASigA=KKACigBKKYE1FD3ExKSgBaKWwBS0eYCUUDCigAooGFFBIUUDCkoGFFACUUgCigQlLTASigBKWgBKKAEpaYBRSADSUICbNJQJhRTQxKKQhaKLgLSUDCigBKUUAFFACUUAFFABRQMKSgQUUAFFACUUCCkoGFFABRQAUlABSUAT0lACGimAtFIQUUALSUDCigBKKAFooASikAUUxiUUCFpKBBRSGJRTsAUUAJRQAUUAFFCAKSgYUUCJqSgQlLQAlFAC0UAFFAwooAKKQBRTASigAoNACUUAFFAwopCCkpgFFABSUAFFABRQAlFAwooES0UABooEJRRcGgpaACloGJRQAUUgEop7gFFAxKKLiCigBKWi4BRQMKSgQUUAFJQAUUAFFACUUAFFAE1JRqAUUAJRQIKU0MdwooEFFDQopjClpAFFABSUALSUgCigAopjCkoAKKBC0lACUtACUUAJRQMKKACkoEJS0AFFABSUAT0lAhKKACijUAooAWigYUUAFJQAUUAFFABSUAFFABRSAKKYxKSgAooEFFABRQIKKBiUUAFJRYCekpiCikAlFAwooAXtSUALSUALSUIAooAKKACigBKKACkoAWkoAKKACkoAKSgAooAKKBiUUCCkoAmooJEooKCjJ7UxCUtIYUUAFFABRQAUUDCigQlLQAlJQAtJQAUUDCkoEFFABSUAFFABRQAUUDEooAnpKGSJRQMWkoASnUCEpaBhRQISigYUlAwpaACkpCCimAUlABRQAUVACUUAFFAwooEJSUDCigQUlABRQAlFAE9JQJiUUDFpKACloEJS0DCigQUlABRQAUlAwooAKKBCUUDCigQUlABRQAUlABRQAUlAE1FMgKKCgooEFFABRQAUtAxKKACigQUUDCkoAKKACigAooASigAooASigAooASigAooASigD//2Q=="

try:
    # 去除可能存在的 MIME 类型前缀
    if "base64," in base64_str:
        base64_data = base64_str.split("base64,")[-1]
        print("1")
    else:
        base64_data = base64_str

    # 解码 Base64 数据
    binary_data = base64.b64decode(base64_data)
    
    # 验证有效性（可选）
    if binary_data[:3] == b'\xff\xd8\xff':
        print("解码成功：检测到 JPEG 文件头 (FF D8 FF)")
    else:
        print("警告：二进制数据不以标准JPEG文件头开始")

except (binascii.Error, TypeError) as e:
    print(f"解码失败：无效的 Base64 数据 ({str(e)})")
except Exception as e:
    print(f"发生意外错误：{str(e)}")


timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
filename = f"esp32cam_{timestamp}.jpg"
save_path = UPLOAD_FOLDER + filename
# 保存为文件验证（可选）
with open(save_path, "wb") as f:
    f.write(binary_data)
    print("已保存为 output.jpg")